#ifndef CONFIG_H
#define CONFIG_H

#define WINDOW_WIDTH 1280
#define WINDOW_HEIGHT 720
#define MARGIN_LEFT 60
#define MARGIN_RIGHT 20
#define MARGIN_TOP 64
#define MARGIN_BOTTOM 48
#define GRID_COLOR (Color){40, 40, 40, 96}

#define BAR_PIXEL_WIDTH 6
#define BAR_GAP 2

#define DB_BOTTOM -60.0
#define DB_TOP 0.0
#define DB_OFFSET 0.0

#define FFT_WINDOW_SIZE 8192
#define FFT_HOP_SIZE (FFT_WINDOW_SIZE / 16)
#define HPF_CUTOFF_HZ 1.0
#define SMOOTH_ATTACK_MS 0.0
#define SMOOTH_RELEASE_MS 250.0

#define DB_SMOOTH_ATTACK_MS 10.0
#define DB_SMOOTH_RELEASE_MS 250.0

#define PEAK_HOLD_SEC 0.75
#define PEAK_DECAY_DB_PER_SEC 1.5
#define EPSILON_POWER 1e-12

#define DEFAULT_SPL_OFFSET_DB 0.0
#define DEFAULT_CALIBRATOR_TARGET_DB_SPL 94.0

#define METER_READOUT_SMOOTH_MS 350.0
#define CURSOR_READOUT_SMOOTH_MS 250.0

#define INPUT_SAMPLE_RATE 44100
#define INPUT_FRAMES_PER_BUFFER 1024
#define INPUT_NUM_CHANNELS 1

#endif
