name: release

on:
  push:
    tags:
      - "v*"

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update
      - name: Build and install Raylib from source
        run: |
          git clone https://github.com/raysan5/raylib.git
          cd raylib
          mkdir build && cd build
          cmake ..
          make -j$(nproc)
          sudo make install
      - run: sudo apt-get install -y clang pkg-config libfftw3-dev
      - name: Build
        run: |
          mkdir -p build
          clang -std=c99 -O3 -march=native -Wall -Wextra -Werror \
            -I./include \
            ./src/main.c \
            -o ./build/c_fft_visualizer \
            $(pkg-config --cflags --libs raylib fftw3) -lm -lpthread
          cp -r assets ./build/
      - name: Package
        run: |
          mkdir -p dist
          tar -C build -czf dist/c_fft_visualizer-linux-x86_64.tar.gz c_fft_visualizer assets
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/c_fft_visualizer-linux-x86_64.tar.gz
