name: release

on:
  push:
    tags:
      - "v*"

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update
      - run: sudo apt-get install -y clang pkg-config libfftw3-dev libraylib-dev
      - name: Build
        run: |
          mkdir -p build
          clang -std=c99 -O3 -Wall -Wextra -Werror \
            -I./include \
            ./src/main.c \
            -o ./build/c_fft_visualizer \
            $(pkg-config --cflags --libs raylib fftw3) -lm -lpthread
          cp -r assets ./build/
      - name: Package
        run: |
          mkdir -p dist
          tar -C build -czf dist/c_fft_visualizer-linux-x86_64.tar.gz c_fft_visualizer assets
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/c_fft_visualizer-linux-x86_64.tar.gz

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: brew update
      - run: brew install llvm fftw raylib
      - name: Build
        env:
          CC: clang
        run: |
          mkdir -p build
          clang -std=c99 -O3 -Wall -Wextra -Werror \
            -I./include \
            ./src/main.c \
            -o ./build/c_fft_visualizer \
            -lraylib -lfftw3 \
            -framework OpenGL -framework Cocoa -framework IOKit -framework CoreVideo -framework CoreAudio -framework AudioToolbox
          cp -r assets ./build/
      - name: Package
        run: |
          mkdir -p dist
          ARCH="$(uname -m)"
          (cd build && zip -r ../dist/c_fft_visualizer-macos-$ARCH.zip c_fft_visualizer assets)
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/c_fft_visualizer-macos-*.zip

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          install: >-
            git
            mingw-w64-x86_64-clang
            mingw-w64-x86_64-raylib
            mingw-w64-x86_64-fftw
      - name: Build
        shell: msys2 {0}
        run: |
          mkdir -p build
          clang -std=c99 -O3 -Wall -Wextra -Werror \
            -I./include \
            ./src/main.c \
            -o ./build/c_fft_visualizer.exe \
            -lraylib -lfftw3 -lopengl32 -lgdi32 -lwinmm -lws2_32
          cp -r assets build/
      - name: Package
        shell: msys2 {0}
        run: |
          mkdir -p dist
          cd build
          7z a ../dist/c_fft_visualizer-windows-x86_64.zip c_fft_visualizer.exe assets
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/c_fft_visualizer-windows-x86_64.zip
